import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'

import './globals.css'
import { cn } from '@/utils'
import { Navbar } from '@/components'
import Providers from '@/config/provider'

const comfortaa = Comfortaa({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  display: 'swap',
  variable: '--font-comfortaa',
})

// create a custom metadata later
export const metadata: Metadata = {
  title: 'Flash!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'bg-white text-slate-900 antialiased light',
        comfortaa.className
      )}
    >
      <Providers>
        <body
          className={cn(
            'min-h-screen pt-12 bg-slate-50 antialiased w-full overflow-x-hidden'
          )}
        >
          <Navbar />
          <div className="container max-w-7xl mx-auto h-full pt-12">
            {children}
          </div>
        </body>
      </Providers>
    </html>
  )
}
